services:
  chess:
    container_name: chess
    build:
      context: ./omega-chess/
    image: chess:1.0
    networks:
      - default
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f https://localhost/api/health || exit 1"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s

  mongo:
    image: mongo:latest
    container_name: mongo
    networks:
      - default
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - /usr/mongodb:/data/db

  tbot:
    container_name: tbot
    build:
      context: ./telegram-bot-server/
    image: tbot:1.0
    networks:
      - default
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f https://localhost/health || exit 1"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
  
  db-backend:
    container_name: darkboard-backend
    build:
      context: ./darkboard-backend/
    image: darkboard-backend:1.0
    networks:
      - default
    restart: unless-stopped

  nginx:
    user: root
    container_name: nginx
    image: nginx
    volumes:
      - ./nginx/default_https.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt/:/etc/letsencrypt/
    ports:
      - "80:80"
      - "443:443"
    restart: always
    networks:
      - default
    healthcheck:
      test: ["CMD", "service", "nginx", "status"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s